#Build and Test
FROM maven:3.9.6-eclipse-temurin-21

# Set working directory
WORKDIR /app

# install edge browser
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && \
    install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ && \
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list' && \
    apt-get update && \
    apt install -y microsoft-edge-stable && \
    rm microsoft.gpg

# Copy the project files into the container
COPY . .

# Compile
RUN mvn clean compile

# Now define the test command to run **when the container is executed**
CMD ["mvn", "test", "-Dsurefire.suiteXmlFiles=src/test/resources/testng_suites/edge_specific_suites/edge_add_to_cart_tests.xml"]

