name: CI/CD pipeline - DemoBlaze Automation Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge]  # This run tests on Chrome and Edge in parallel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        # This step caches Maven dependencies to prevent downloading them every time the workflow runs.

      - name: Install dependencies using Maven
        run: mvn install

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Install ChromeDriver for Linux
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chromedriver-linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Set up Edge browser
        uses: microsoft/setup-msbuild@v1 
        with:
          vs-version: 'latest'
          msbuild-version: 'latest'

      - name: Install EdgeDriver for Linux
        run: |
          wget https://msedgedriver.azureedge.net/133.0.3065.69/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Run tests on ${{ matrix.browser }}
        run: mvn test -Dbrowser=${{ matrix.browser }} # Pass the browser as a system property to the test
